name: Test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  print:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps: 
      - name: echo "test"
        shell: bash
        run: echo "test master branch"
