name: Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell:
        run: echo "test step 1"
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: echo "test"
        shell: bash
        run: echo "test master branch"